name: dementia_care_app
description: A Flutter application for dementia patient care.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---------------- STATE MANAGEMENT ----------------
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.5

  # ---------------- SUPABASE ----------------
  supabase_flutter: ^2.5.6

  # ---------------- LOCAL STORAGE ----------------
  
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

  # ---------------- AUDIO ----------------
  record: ^6.2.0
  audioplayers: ^6.0.0
  just_audio: ^0.10.5
  path_provider: ^2.1.3

  # ---------------- LOCATION & MAPS ----------------
  geolocator: ^14.0.2
  google_maps_flutter: ^2.6.1
  flutter_background_geolocation: ^5.0.4

  # ---------------- IMAGES & MEDIA ----------------
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0

  # ---------------- NOTIFICATIONS ----------------
  flutter_local_notifications: ^20.0.0
  firebase_messaging: ^16.1.1
  permission_handler: ^12.0.1

  # ---------------- UI ----------------
  fl_chart: ^1.1.1
  carousel_slider: ^5.1.2
  flip_card: ^0.7.0
  confetti: ^0.8.0
  shimmer: ^3.0.0
  google_fonts: ^8.0.1

  # ---------------- UTILITIES ----------------
  device_info_plus: ^12.3.0
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  uuid: ^4.4.0
  flutter_dotenv: ^6.0.0

  # ---------------- NAVIGATION ----------------
  go_router: ^17.1.0

  # ---------------- CONNECTIVITY ----------------
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^3.0.1
  curved_nav_bar: ^0.0.2
  curved_navigation_bar: ^1.0.6
  qr_flutter: ^4.1.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  build_runner: ^2.4.13
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  flutter_local_notifications_platform_interface: ^10.0.0
  flutter_local_notifications_windows: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/Gemini_Generated_Image_sz8u71sz8u71sz8u.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/games/
    - assets/images/placeholders/
    - assets/icons/
    - assets/sounds/
    - assets/fonts/
    - assets/app_icon/
